### ISSUE TITLE
Filter not working!!

### ISSUE THREAD

**Issue by aminecherif94** [GalAvineri/ISIC-Archive-Downloader#15]
The following command to choose between benign or malignant from the datasets does not work:

python download_archive.py --filter benign

Getting the following error:
Traceback (most recent call last):
  File "download_archive.py", line 254, in <module>
    main(sys.argv[1:])
  File "download_archive.py", line 248, in main
    seg_skill=args.seg_skill, num_processes=args.p)
  File "download_archive.py", line 36, in download_archive
    descs_dir=descs_dir)
  File "download_archive.py", line 138, in download_descriptions_and_filter
    ImgDownloader.save_description(description, descs_dir)
AttributeError: type object 'LesionImageDownloader' has no attribute 'save_description'

**Comment by fabiomaia** [comment]
Works well for me. I think you can close.

**Comment by GalAvineri** [comment]
Thanks! closing than :)
